version: "3.8"
services:
  db-mysql:
    tty: true
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE #  incluir as regras necessárias para permitir o que o MySQL execute functions
    container_name: mysql-crud
    environment:
      MYSQL_ROOT_PASSWORD: db-#12.bas
    volumes:
      - ./db-mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

